/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    forms: Form;
    submissions: Submission;
    'form-uploads': FormUpload;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'form-uploads': FormUploadsSelect<false> | FormUploadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Form fields become locked once a form has submissions or connected data
   */
  locked?: boolean | null;
  confirmationType?: ('redirect' | 'message') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirectUrl?: string | null;
  redirect?: string | null;
  notification?:
    | {
        email: string;
        subject: string;
        message: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        conditions?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  formSchema?: Record<string, unknown> | null;
  pages?: {
    id: string;
    backButton?: string;
    nextButton?: string;
    rows: {
      id: string;
      columns: (
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'text';
            defaultValue?: string;
            maxLength?: number;
            minLength?: number;
            placeholder?: string;
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'textarea';
            defaultValue?: string;
            maxLength?: number;
            minLength?: number;
            placeholder?: string;
            rows: number;
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'email';
            defaultValue?: string;
            placeholder?: string;
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'number';
            defaultValue?: number;
            max?: number;
            min?: number;
            placeholder?: string;
            step?: number;
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'checkbox';
            defaultValue?: string[];
            options: {
              label: string;
              value: string;
            }[];
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'radio';
            defaultValue?: string;
            options: {
              label: string;
              value: string;
            }[];
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'select';
            defaultValue?: string;
            options: {
              label: string;
              value: string;
            }[];
            placeholder?: string;
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'date';
            defaultValue?: string;
            maxDate?: string;
            minDate?: string;
            placeholder?: string;
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'file';
            allowedFileTypes?: string;
            maxFiles?: number;
            maxFileSize?: number;
            multiple?: boolean;
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'toggle';
            defaultValue?: boolean;
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'consent';
            defaultValue?: boolean;
          }
        | {
            id: string;
            type: 'message';
            _draft?: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            richText?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: 'ltr' | 'rtl' | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
            };
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'array';
            maxRows?: number;
            minRows?: number;
            rows: {
              id: string;
              columns: (
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'text';
                    defaultValue?: string;
                    maxLength?: number;
                    minLength?: number;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'textarea';
                    defaultValue?: string;
                    maxLength?: number;
                    minLength?: number;
                    placeholder?: string;
                    rows: number;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'email';
                    defaultValue?: string;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'number';
                    defaultValue?: number;
                    max?: number;
                    min?: number;
                    placeholder?: string;
                    step?: number;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'checkbox';
                    defaultValue?: string[];
                    options: {
                      label: string;
                      value: string;
                    }[];
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'radio';
                    defaultValue?: string;
                    options: {
                      label: string;
                      value: string;
                    }[];
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'select';
                    defaultValue?: string;
                    options: {
                      label: string;
                      value: string;
                    }[];
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'date';
                    defaultValue?: string;
                    maxDate?: string;
                    minDate?: string;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'file';
                    allowedFileTypes?: string;
                    maxFiles?: number;
                    maxFileSize?: number;
                    multiple?: boolean;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'toggle';
                    defaultValue?: boolean;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'consent';
                    defaultValue?: boolean;
                  }
              )[];
            }[];
          }
        | {
            id: string;
            name: string;
            _draft?: boolean;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'group';
            rows: {
              id: string;
              columns: (
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'text';
                    defaultValue?: string;
                    maxLength?: number;
                    minLength?: number;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'textarea';
                    defaultValue?: string;
                    maxLength?: number;
                    minLength?: number;
                    placeholder?: string;
                    rows: number;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'email';
                    defaultValue?: string;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'number';
                    defaultValue?: number;
                    max?: number;
                    min?: number;
                    placeholder?: string;
                    step?: number;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'checkbox';
                    defaultValue?: string[];
                    options: {
                      label: string;
                      value: string;
                    }[];
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'radio';
                    defaultValue?: string;
                    options: {
                      label: string;
                      value: string;
                    }[];
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'select';
                    defaultValue?: string;
                    options: {
                      label: string;
                      value: string;
                    }[];
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'date';
                    defaultValue?: string;
                    maxDate?: string;
                    minDate?: string;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'file';
                    allowedFileTypes?: string;
                    maxFiles?: number;
                    maxFileSize?: number;
                    multiple?: boolean;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'toggle';
                    defaultValue?: boolean;
                  }
                | {
                    id: string;
                    name: string;
                    _draft?: boolean;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'consent';
                    defaultValue?: boolean;
                  }
              )[];
            }[];
          }
      )[];
    }[];
    title: string;
  }[];
  /**
   * Schema path used for rich text content field (message)
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  /**
   * Auto-generated from form title at submission time
   */
  title: string;
  /**
   * Identifier for the submitter (e.g., email address)
   */
  from?: string | null;
  /**
   * Reference to parent form (for grouping/queries)
   */
  form?: (number | null) | Form;
  submissionData: Record<string, any> | null;
  formSnapshot?: Record<string, any> | null;
  userAgent?: string | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Files uploaded via form submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-uploads".
 */
export interface FormUpload {
  id: number;
  /**
   * The form this file was uploaded through
   */
  form?: (number | null) | Form;
  /**
   * The submission this file belongs to
   */
  submission?: (number | null) | Submission;
  /**
   * The form field name this file was uploaded to
   */
  fieldName?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'form-uploads';
        value: number | FormUpload;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  locked?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirectUrl?: T;
  redirect?: T;
  notification?:
    | T
    | {
        email?: T;
        subject?: T;
        message?: T;
        conditions?: T;
        id?: T;
      };
  formSchema?: T;
  pages?: T;
  richText?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  title?: T;
  from?: T;
  form?: T;
  submissionData?: T;
  formSnapshot?: T;
  userAgent?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-uploads_select".
 */
export interface FormUploadsSelect<T extends boolean = true> {
  form?: T;
  submission?: T;
  fieldName?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}